### ISSUE TITLE
Error on npm run develop

### ISSUE THREAD

**Issue by MateThemes** [r-ichard/gatsby-starter-bootstrap-5#18]
Hello!

I cloned the repo for my new gatsby project and I got an error on npm run develop

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: @r-ichard/gatsby-starter-bootstrap-5@2.0.1
npm ERR! Found: gatsby@5.1.0
npm ERR! node_modules/gatsby
npm ERR!   gatsby@"^5.0.0-next.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer gatsby@"^4.0.0-next" from gatsby-plugin-offline@5.24.0
npm ERR! node_modules/gatsby-plugin-offline
npm ERR!   gatsby-plugin-offline@"^5.0.0-next" from the root project`

Is there a workaround get the development running?

Thanks

**Comment by r-ichard** [comment]
Hi @MateThemes  

Thanks a lot for reporting this issue ! I will look into this asap !

**Comment by r-ichard** [comment]
This should be solved on version 2.0.2
